### ISSUE TITLE
Wunschheft vs Pflichtenheft erfassen

### ISSUE THREAD

**Issue by glaand** [IBZTI2018/TI3-WT-SA#43]

**Comment by cybrox** [comment]
Als **Product Owner** möchte ich, dass die Wunsch und Pflichtziele getrennt ersichtlich sind.

**Acceptance Criterias**

* Epic-Liste soll tabellarisch zusammengefasst werden mit muss / wunsch

**Tasks**

* [ ] Epic liste tabellarisch zusammenfassen
* [ ] Epic liste in Use-Cases aufteilen (SCRUM Epics sind quas Use-Cases)
