### ISSUE TITLE
Klassendiagramm MVC Framework

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#46]
Als **Entwickler** möchte ich eine saubere Dokumentation des selbst erstellten Frameworks haben.

**Acceptance-Criterias**
- Ein komplettes Klassendiagramm des Frameworks muss vorhanden sein

**Comment by glaand** [comment]
https://github.com/IBZTI2018/TI3-WT-SA/tree/story-46
